# Generated by Django 5.0.6 on 2026-08-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji shown on the site', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant')], default='hotel', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_type', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Family', 'Family')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('bed_type', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, help_text="e.g. '150 sq ft'", max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenity strings')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image_url', models.URLField(blank=True, help_text='External URL fallback, used for seed/demo data')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.room')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
